build/hashtable: hashtable.o hashtable_type_util_charp.o hashtable_type_util_charp_java.o main.o
	


build/hashtable.o: src/hashtable.c include/hashtable.h

build/hashtable_type_util_charp.o: src/hashtable_type_util_charp.c include/hashtable_type_util_charp.h

build/hashtable_type_util_charp_java.o: src/hashtable_type_util_charp_java.c include/hashtable_type_util_charp_java.h

build/main.o: src/main.c include/hashtable.h \
 include/hashtable_type_util_charp.h \
 include/hashtable_type_util_charp_java.h


